spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book-network
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: sql_server
  mail:
    host: localhost
    port: 1025
    username: mayuravel
    password: Mayu@1999
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: B648DD88CE0EE1921CC8BCD06C2C44B16CDFEAA5C72BE54198933DAB0B7F94BA
      expiration: 8640000
  mailing:
    frontend:
      activationUrl: http://localhost:4200/activate-account